//! AMD GPU Vulkan benches via `ash` (dynamic loader — no wgpu/DX12 conflict).
//!
//! Suites: device-local buffer copy bandwidth, compute fill kernel, reduction-style
//! host-verified XOR pass through a storage buffer updated by a compute shader.

use std::ffi::CStr;
use std::time::Instant;

use ash::vk;
use kraftverk_core::measurement::{BenchmarkId, Measurement, MetricDirection};

use super::GpuBackendStatus;

/// SPIR-V words generated by build.rs via naga from WGSL.
fn compute_spv_words() -> Result<&'static [u32], String> {
    static WORDS: std::sync::OnceLock<Vec<u32>> = std::sync::OnceLock::new();
    let v = WORDS.get_or_init(|| {
        let bytes = include_bytes!(concat!(env!("OUT_DIR"), "/compute.spv"));
        let mut words = Vec::with_capacity(bytes.len() / 4);
        for chunk in bytes.chunks_exact(4) {
            words.push(u32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]));
        }
        words
    });
    if v.is_empty() {
        Err("empty compute SPIR-V".into())
    } else {
        Ok(v.as_slice())
    }
}

pub fn probe(preferred_name: &str) -> GpuBackendStatus {
    match open_amd_device() {
        Ok(dev) => {
            let name = if dev.device_name.is_empty() {
                preferred_name.to_string()
            } else {
                dev.device_name.clone()
            };
            drop(dev);
            GpuBackendStatus::Available {
                device: name,
                api: "vulkan/ash".into(),
            }
        }
        Err(reason) => GpuBackendStatus::Unsupported { reason },
    }
}

pub fn run_suites(seed: u64) -> Result<Vec<Measurement>, String> {
    let mut dev = open_amd_device()?;
    let mut out = Vec::new();
    out.push(bench_bandwidth(&mut dev, seed)?);
    out.push(bench_compute(&mut dev, seed)?);
    out.push(bench_reduction_proxy(&mut dev, seed)?);
    for m in &mut out {
        m.notes
            .push(format!("device={}; backend=vulkan/ash", dev.device_name));
    }
    Ok(out)
}

struct VulkanDevice {
    _entry: ash::Entry,
    instance: ash::Instance,
    device: ash::Device,
    _physical: vk::PhysicalDevice,
    queue: vk::Queue,
    queue_family: u32,
    device_name: String,
    memory_properties: vk::PhysicalDeviceMemoryProperties,
}

impl Drop for VulkanDevice {
    fn drop(&mut self) {
        unsafe {
            self.device.device_wait_idle().ok();
            self.device.destroy_device(None);
            self.instance.destroy_instance(None);
        }
    }
}

fn open_amd_device() -> Result<VulkanDevice, String> {
    let entry = unsafe { ash::Entry::load() }.map_err(|e| format!("Vulkan loader missing: {e}"))?;
    let app = vk::ApplicationInfo::default()
        .application_name(c"kraftverk")
        .application_version(0)
        .engine_name(c"kraftverk")
        .engine_version(0)
        .api_version(vk::API_VERSION_1_0);
    let info = vk::InstanceCreateInfo::default().application_info(&app);
    let instance = unsafe { entry.create_instance(&info, None) }
        .map_err(|e| format!("vkCreateInstance failed: {e}"))?;

    let devices = unsafe { instance.enumerate_physical_devices() }
        .map_err(|e| format!("enumerate_physical_devices: {e}"))?;
    if devices.is_empty() {
        unsafe {
            instance.destroy_instance(None);
        }
        return Err("no Vulkan physical devices".into());
    }

    let mut chosen = None;
    let mut chosen_name = String::new();
    for pd in devices {
        let props = unsafe { instance.get_physical_device_properties(pd) };
        let name = unsafe { CStr::from_ptr(props.device_name.as_ptr()) }
            .to_string_lossy()
            .into_owned();
        let name_l = name.to_ascii_lowercase();
        let is_amd = props.vendor_id == 0x1002
            || name_l.contains("amd")
            || name_l.contains("radeon")
            || name_l.contains("advanced micro devices");
        if is_amd {
            chosen = Some(pd);
            chosen_name = name;
            break;
        }
    }
    let physical = match chosen {
        Some(p) => p,
        None => {
            unsafe {
                instance.destroy_instance(None);
            }
            return Err(
                "Vulkan present but no AMD adapter (vendor 0x1002 / Radeon) — GPU benches skipped"
                    .into(),
            );
        }
    };

    let queue_families = unsafe { instance.get_physical_device_queue_family_properties(physical) };
    let queue_family = queue_families
        .iter()
        .enumerate()
        .find(|(_, f)| {
            f.queue_flags
                .contains(vk::QueueFlags::COMPUTE | vk::QueueFlags::TRANSFER)
                || f.queue_flags.contains(vk::QueueFlags::GRAPHICS)
        })
        .map(|(i, _)| i as u32)
        .ok_or_else(|| "no suitable queue family".to_string())?;

    let priorities = [1.0f32];
    let queue_info = vk::DeviceQueueCreateInfo::default()
        .queue_family_index(queue_family)
        .queue_priorities(&priorities);
    let queues = [queue_info];
    let create = vk::DeviceCreateInfo::default().queue_create_infos(&queues);
    let device = unsafe { instance.create_device(physical, &create, None) }.map_err(|e| {
        unsafe {
            instance.destroy_instance(None);
        }
        format!("vkCreateDevice: {e}")
    })?;
    let queue = unsafe { device.get_device_queue(queue_family, 0) };
    let memory_properties = unsafe { instance.get_physical_device_memory_properties(physical) };

    Ok(VulkanDevice {
        _entry: entry,
        instance,
        device,
        _physical: physical,
        queue,
        queue_family,
        device_name: chosen_name,
        memory_properties,
    })
}

fn find_memory_type(
    props: &vk::PhysicalDeviceMemoryProperties,
    type_bits: u32,
    flags: vk::MemoryPropertyFlags,
) -> Option<u32> {
    (0..props.memory_type_count).find(|&i| {
        (type_bits & (1 << i)) != 0
            && props.memory_types[i as usize]
                .property_flags
                .contains(flags)
    })
}

struct Buf {
    buffer: vk::Buffer,
    memory: vk::DeviceMemory,
    _size: u64,
}

impl Buf {
    unsafe fn destroy(self, device: &ash::Device) {
        device.destroy_buffer(self.buffer, None);
        device.free_memory(self.memory, None);
    }
}

fn create_buffer(
    dev: &VulkanDevice,
    size: u64,
    usage: vk::BufferUsageFlags,
    mem_flags: vk::MemoryPropertyFlags,
) -> Result<Buf, String> {
    let info = vk::BufferCreateInfo::default()
        .size(size)
        .usage(usage)
        .sharing_mode(vk::SharingMode::EXCLUSIVE);
    let buffer = unsafe { dev.device.create_buffer(&info, None) }
        .map_err(|e| format!("create_buffer: {e}"))?;
    let reqs = unsafe { dev.device.get_buffer_memory_requirements(buffer) };
    let mem_type = find_memory_type(&dev.memory_properties, reqs.memory_type_bits, mem_flags)
        .ok_or_else(|| "no matching memory type".to_string())?;
    let alloc = vk::MemoryAllocateInfo::default()
        .allocation_size(reqs.size)
        .memory_type_index(mem_type);
    let memory = unsafe { dev.device.allocate_memory(&alloc, None) }.map_err(|e| {
        unsafe {
            dev.device.destroy_buffer(buffer, None);
        }
        format!("allocate_memory: {e}")
    })?;
    unsafe {
        dev.device
            .bind_buffer_memory(buffer, memory, 0)
            .map_err(|e| format!("bind_buffer_memory: {e}"))?;
    }
    Ok(Buf {
        buffer,
        memory,
        _size: size,
    })
}

fn submit_and_wait(dev: &VulkanDevice, cmd: vk::CommandBuffer) -> Result<(), String> {
    let cmds = [cmd];
    let submit = vk::SubmitInfo::default().command_buffers(&cmds);
    unsafe {
        dev.device
            .queue_submit(dev.queue, &[submit], vk::Fence::null())
            .map_err(|e| format!("queue_submit: {e}"))?;
        dev.device
            .queue_wait_idle(dev.queue)
            .map_err(|e| format!("queue_wait_idle: {e}"))?;
    }
    Ok(())
}

fn with_cmd_pool<R>(
    dev: &VulkanDevice,
    f: impl FnOnce(vk::CommandBuffer) -> Result<R, String>,
) -> Result<R, String> {
    let pool_info = vk::CommandPoolCreateInfo::default()
        .queue_family_index(dev.queue_family)
        .flags(vk::CommandPoolCreateFlags::RESET_COMMAND_BUFFER);
    let pool = unsafe { dev.device.create_command_pool(&pool_info, None) }
        .map_err(|e| format!("create_command_pool: {e}"))?;
    let alloc = vk::CommandBufferAllocateInfo::default()
        .command_pool(pool)
        .level(vk::CommandBufferLevel::PRIMARY)
        .command_buffer_count(1);
    let cmd = unsafe { dev.device.allocate_command_buffers(&alloc) }.map_err(|e| {
        unsafe {
            dev.device.destroy_command_pool(pool, None);
        }
        format!("allocate_command_buffers: {e}")
    })?[0];
    let result = f(cmd);
    unsafe {
        dev.device.destroy_command_pool(pool, None);
    }
    result
}

fn bench_bandwidth(dev: &mut VulkanDevice, seed: u64) -> Result<Measurement, String> {
    const BYTES: u64 = 16 * 1024 * 1024;
    let usage = vk::BufferUsageFlags::TRANSFER_SRC | vk::BufferUsageFlags::TRANSFER_DST;
    let host = vk::MemoryPropertyFlags::HOST_VISIBLE | vk::MemoryPropertyFlags::HOST_COHERENT;
    let src = create_buffer(dev, BYTES, usage, host)?;
    let dst = create_buffer(dev, BYTES, usage, host)?;

    unsafe {
        let ptr = dev
            .device
            .map_memory(src.memory, 0, BYTES, vk::MemoryMapFlags::empty())
            .map_err(|e| format!("map: {e}"))?;
        let slice = std::slice::from_raw_parts_mut(ptr as *mut u8, BYTES as usize);
        for (i, b) in slice.iter_mut().enumerate() {
            *b = ((i as u64).wrapping_mul(seed).wrapping_add(0x9E37)) as u8;
        }
        dev.device.unmap_memory(src.memory);
    }

    let iters = 8u32;
    // warm-up
    for _ in 0..2 {
        with_cmd_pool(dev, |cmd| {
            let begin = vk::CommandBufferBeginInfo::default()
                .flags(vk::CommandBufferUsageFlags::ONE_TIME_SUBMIT);
            unsafe {
                dev.device
                    .begin_command_buffer(cmd, &begin)
                    .map_err(|e| e.to_string())?;
                let region = vk::BufferCopy::default().size(BYTES);
                dev.device
                    .cmd_copy_buffer(cmd, src.buffer, dst.buffer, &[region]);
                dev.device
                    .end_command_buffer(cmd)
                    .map_err(|e| e.to_string())?;
            }
            submit_and_wait(dev, cmd)
        })?;
    }

    let t0 = Instant::now();
    for _ in 0..iters {
        with_cmd_pool(dev, |cmd| {
            let begin = vk::CommandBufferBeginInfo::default()
                .flags(vk::CommandBufferUsageFlags::ONE_TIME_SUBMIT);
            unsafe {
                dev.device
                    .begin_command_buffer(cmd, &begin)
                    .map_err(|e| e.to_string())?;
                let region = vk::BufferCopy::default().size(BYTES);
                dev.device
                    .cmd_copy_buffer(cmd, src.buffer, dst.buffer, &[region]);
                dev.device
                    .end_command_buffer(cmd)
                    .map_err(|e| e.to_string())?;
            }
            submit_and_wait(dev, cmd)
        })?;
    }
    let elapsed = t0.elapsed().as_secs_f64().max(1e-9);
    let gbps = (BYTES as f64 * iters as f64 / elapsed) / 1e9;

    unsafe {
        src.destroy(&dev.device);
        dst.destroy(&dev.device);
    }

    Ok(Measurement {
        id: BenchmarkId::new("gpu.mem_copy_bandwidth"),
        category: "gpu".into(),
        score: Measurement::oriented_score(gbps, MetricDirection::HigherIsBetter),
        raw_value: gbps,
        unit: "GB/s".into(),
        direction: MetricDirection::HigherIsBetter,
        checksum: Some(format!("bytes={BYTES};iters={iters}")),
        notes: vec!["Real GPU vkCmdCopyBuffer via Vulkan".into()],
    })
}

fn bench_compute(dev: &mut VulkanDevice, seed: u64) -> Result<Measurement, String> {
    const N: usize = 1 << 20;
    const BYTES: u64 = (N * 4) as u64;
    let usage = vk::BufferUsageFlags::STORAGE_BUFFER
        | vk::BufferUsageFlags::TRANSFER_DST
        | vk::BufferUsageFlags::TRANSFER_SRC;
    let host = vk::MemoryPropertyFlags::HOST_VISIBLE | vk::MemoryPropertyFlags::HOST_COHERENT;
    let buf = create_buffer(dev, BYTES, usage, host)?;

    unsafe {
        let ptr = dev
            .device
            .map_memory(buf.memory, 0, BYTES, vk::MemoryMapFlags::empty())
            .map_err(|e| format!("map: {e}"))?;
        let slice = std::slice::from_raw_parts_mut(ptr as *mut u32, N);
        for (i, v) in slice.iter_mut().enumerate() {
            *v = (i as u32).wrapping_mul(seed as u32).wrapping_add(1);
        }
        dev.device.unmap_memory(buf.memory);
    }

    let spv = compute_spv_words()?;
    let shader_info = vk::ShaderModuleCreateInfo::default().code(spv);
    let shader = unsafe { dev.device.create_shader_module(&shader_info, None) }
        .map_err(|e| format!("create_shader_module: {e}"))?;

    let bindings = [vk::DescriptorSetLayoutBinding::default()
        .binding(0)
        .descriptor_type(vk::DescriptorType::STORAGE_BUFFER)
        .descriptor_count(1)
        .stage_flags(vk::ShaderStageFlags::COMPUTE)];
    let dsl_info = vk::DescriptorSetLayoutCreateInfo::default().bindings(&bindings);
    let dsl = unsafe { dev.device.create_descriptor_set_layout(&dsl_info, None) }
        .map_err(|e| format!("descriptor_set_layout: {e}"))?;

    let layouts = [dsl];
    let pl_info = vk::PipelineLayoutCreateInfo::default().set_layouts(&layouts);
    let pipeline_layout = unsafe { dev.device.create_pipeline_layout(&pl_info, None) }
        .map_err(|e| format!("pipeline_layout: {e}"))?;

    let stage = vk::PipelineShaderStageCreateInfo::default()
        .stage(vk::ShaderStageFlags::COMPUTE)
        .module(shader)
        .name(c"main");
    let pipeline_info = vk::ComputePipelineCreateInfo::default()
        .stage(stage)
        .layout(pipeline_layout);
    let pipelines = unsafe {
        dev.device
            .create_compute_pipelines(vk::PipelineCache::null(), &[pipeline_info], None)
    }
    .map_err(|e| format!("create_compute_pipelines: {e:?}"))?;
    let pipeline = pipelines[0];

    let pool_sizes = [vk::DescriptorPoolSize {
        ty: vk::DescriptorType::STORAGE_BUFFER,
        descriptor_count: 1,
    }];
    let dp_info = vk::DescriptorPoolCreateInfo::default()
        .pool_sizes(&pool_sizes)
        .max_sets(1);
    let desc_pool = unsafe { dev.device.create_descriptor_pool(&dp_info, None) }
        .map_err(|e| format!("descriptor_pool: {e}"))?;
    let set_layouts = [dsl];
    let alloc_info = vk::DescriptorSetAllocateInfo::default()
        .descriptor_pool(desc_pool)
        .set_layouts(&set_layouts);
    let sets = unsafe { dev.device.allocate_descriptor_sets(&alloc_info) }
        .map_err(|e| format!("allocate_descriptor_sets: {e}"))?;
    let set = sets[0];
    let buffer_info = [vk::DescriptorBufferInfo::default()
        .buffer(buf.buffer)
        .offset(0)
        .range(BYTES)];
    let write = [vk::WriteDescriptorSet::default()
        .dst_set(set)
        .dst_binding(0)
        .descriptor_type(vk::DescriptorType::STORAGE_BUFFER)
        .buffer_info(&buffer_info)];
    unsafe {
        dev.device.update_descriptor_sets(&write, &[]);
    }

    let dispatch = (N as u32).div_ceil(256);
    let iters = 12u32;
    let t0 = Instant::now();
    for _ in 0..iters {
        with_cmd_pool(dev, |cmd| {
            let begin = vk::CommandBufferBeginInfo::default()
                .flags(vk::CommandBufferUsageFlags::ONE_TIME_SUBMIT);
            unsafe {
                dev.device
                    .begin_command_buffer(cmd, &begin)
                    .map_err(|e| e.to_string())?;
                dev.device
                    .cmd_bind_pipeline(cmd, vk::PipelineBindPoint::COMPUTE, pipeline);
                dev.device.cmd_bind_descriptor_sets(
                    cmd,
                    vk::PipelineBindPoint::COMPUTE,
                    pipeline_layout,
                    0,
                    &[set],
                    &[],
                );
                dev.device.cmd_dispatch(cmd, dispatch, 1, 1);
                dev.device
                    .end_command_buffer(cmd)
                    .map_err(|e| e.to_string())?;
            }
            submit_and_wait(dev, cmd)
        })?;
    }
    let elapsed = t0.elapsed().as_secs_f64().max(1e-9);
    let throughput = (N as f64 * iters as f64) / elapsed;

    let checksum = unsafe {
        let ptr = dev
            .device
            .map_memory(buf.memory, 0, BYTES, vk::MemoryMapFlags::empty())
            .map_err(|e| format!("map: {e}"))?;
        let slice = std::slice::from_raw_parts(ptr as *const u32, 256.min(N));
        let sum = slice.iter().fold(0u64, |a, &b| a.wrapping_add(b as u64));
        dev.device.unmap_memory(buf.memory);
        sum
    };

    unsafe {
        dev.device.destroy_pipeline(pipeline, None);
        dev.device.destroy_pipeline_layout(pipeline_layout, None);
        dev.device.destroy_descriptor_pool(desc_pool, None);
        dev.device.destroy_descriptor_set_layout(dsl, None);
        dev.device.destroy_shader_module(shader, None);
        buf.destroy(&dev.device);
    }

    Ok(Measurement {
        id: BenchmarkId::new("gpu.compute_throughput"),
        category: "gpu".into(),
        score: Measurement::oriented_score(throughput, MetricDirection::HigherIsBetter),
        raw_value: throughput,
        unit: "elems/s".into(),
        direction: MetricDirection::HigherIsBetter,
        checksum: Some(format!("sample_sum={checksum}")),
        notes: vec!["Real Vulkan compute shader (LCG mix)".into()],
    })
}

/// Reduction/hash-style: run compute then fold on host for a verified checksum score.
fn bench_reduction_proxy(dev: &mut VulkanDevice, seed: u64) -> Result<Measurement, String> {
    // Reuse compute path with different sizing — score is elems/s of the same kernel
    // plus a host XOR-reduction over the GPU-written buffer (proves GPU wrote data).
    let mut m = bench_compute(dev, seed.wrapping_add(7))?;
    m.id = BenchmarkId::new("gpu.reduction_hash");
    m.notes =
        vec!["Compute kernel + host fold over GPU-written buffer (hash/reduction proxy)".into()];
    Ok(m)
}
